// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CabinetUnitInput: typeof import('./src/components/cabinet-unit-input.vue')['default']
    CertificationInput: typeof import('./src/components/certification-input.vue')['default']
    CertificationList: typeof import('./src/components/certification-list.vue')['default']
    CertificationUnitInput: typeof import('./src/components/certification-unit-input.vue')['default']
    ContactList: typeof import('./src/components/contact-list.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    OrderListSimple: typeof import('./src/components/order-list-simple.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/search-input.vue')['default']
    SkuInput: typeof import('./src/components/sku-input.vue')['default']
    SkuList: typeof import('./src/components/sku-list.vue')['default']
    Snackbar: typeof import('./src/components/snackbar.vue')['default']
    TableInput: typeof import('./src/components/table-input.vue')['default']
  }
}
